import Note from '../models/Note.js';
const list = (value) => Array.isArray(value) ? value : String(value || '').split(',').map((item) => item.trim()).filter(Boolean);
const slugify = (value) => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
export const getNotes = async (req, res) => { const query = { published: true }; if (req.query.category) query.category = req.query.category; if (req.query.difficulty) query.difficulty = req.query.difficulty; if (req.query.tag) query.tags = req.query.tag; if (req.query.search) query.$or = [{ title: new RegExp(req.query.search, 'i') }, { description: new RegExp(req.query.search, 'i') }]; res.json(await Note.find(query).select('-content').sort({ createdAt: -1 })); };
export const getNote = async (req, res) => { const note = await Note.findOne({ slug: req.params.slug, published: true }).populate('author', 'name'); if (!note) return res.status(404).json({ message: 'Note not found' }); res.json(note); };
export const getAdminNotes = async (_req, res) => res.json(await Note.find().sort({ updatedAt: -1 }));
export const saveNote = async (req, res) => { const data = { ...req.body, tags: list(req.body.tags), slug: slugify(req.body.slug || req.body.title), author: req.user._id }; const duplicate = await Note.findOne({ slug: data.slug }); if (duplicate) return res.status(409).json({ message: 'A note with this slug already exists' }); res.status(201).json(await Note.create(data)); };
export const updateNote = async (req, res) => { const note = await Note.findById(req.params.id); if (!note) return res.status(404).json({ message: 'Note not found' }); Object.assign(note, { ...req.body, ...(req.body.tags !== undefined ? { tags: list(req.body.tags) } : {}), ...(req.body.slug || req.body.title ? { slug: slugify(req.body.slug || req.body.title) } : {}) }); res.json(await note.save()); };
export const deleteNote = async (req, res) => { const note = await Note.findByIdAndDelete(req.params.id); if (!note) return res.status(404).json({ message: 'Note not found' }); res.json({ message: 'Note deleted' }); };
